export const itemsPerPage = 20;

export const teachers = [
  {
    id: 1,
    name: "Ustadh Abdullah Rahman",
    email: "abdullah.r@example.com",
    phone: "+1 (555) 111-2222",
    specialization: "Tajweed & Recitation",
    joinedDate: "2023-01-15",
    classes: ["Beginner Quran", "Intermediate Tajweed"],
    totalStudents: 24,
    activeClasses: 2,
  },
  {
    id: 2,
    name: "Ustadha Maryam Ali",
    email: "maryam.a@example.com",
    phone: "+1 (555) 222-3333",
    specialization: "Quran Memorization",
    joinedDate: "2023-06-20",
    classes: ["Advanced Memorization"],
    totalStudents: 15,
    activeClasses: 1,
  },
  {
    id: 3,
    name: "Ustadh Yusuf Khan",
    email: "yusuf.k@example.com",
    phone: "+1 (555) 333-4444",
    specialization: "Arabic Language",
    joinedDate: "2024-02-10",
    classes: ["Arabic Language"],
    totalStudents: 18,
    activeClasses: 1,
  },
]


export const students = [
  {
    id: 1,
    name: "Aisha Rahman",
    parentName: "Fatima Rahman",
    email: "aisha.r@example.com",
    phone: "+1 (555) 123-4567",
    class: "Beginner Quran",
    enrolledDate: "2025-01-15",
    attendance: "95%",
  },
  {
    id: 2,
    name: "Mohammed Khan",
    parentName: "Ahmed Khan",
    email: "mohammed.k@example.com",
    phone: "+1 (555) 234-5678",
    class: "Beginner Quran",
    enrolledDate: "2025-02-01",
    attendance: "88%",
  },
  {
    id: 3,
    name: "Fatima Ali",
    parentName: "Mariam Ali",
    email: "fatima.a@example.com",
    phone: "+1 (555) 345-6789",
    class: "Intermediate Tajweed",
    enrolledDate: "2024-09-10",
    attendance: "92%",
  },
  {
    id: 4,
    name: "Omar Hassan",
    parentName: "Yusuf Hassan",
    email: "omar.h@example.com",
    phone: "+1 (555) 456-7890",
    class: "Beginner Quran",
    enrolledDate: "2025-03-20",
    attendance: "78%",
  },
  {
    id: 5,
    name: "Zainab Ahmed",
    parentName: "Khadija Ahmed",
    email: "zainab.a@example.com",
    phone: "+1 (555) 567-8901",
    class: "Advanced Memorization",
    enrolledDate: "2024-08-05",
    attendance: "100%",
  },
  {
    id: 6,
    name: "Ibrahim Malik",
    parentName: "Amina Malik",
    email: "ibrahim.m@example.com",
    phone: "+1 (555) 678-9012",
    class: "Intermediate Tajweed",
    enrolledDate: "2024-11-12",
    attendance: "85%",
  },
  {
    id: 7,
    name: "Maryam Siddiqui",
    parentName: "Hassan Siddiqui",
    email: "maryam.s@example.com",
    phone: "+1 (555) 789-0123",
    class: "Advanced Memorization",
    enrolledDate: "2024-07-22",
    attendance: "94%",
  },
  {
    id: 8,
    name: "Yusuf Patel",
    parentName: "Layla Patel",
    email: "yusuf.p@example.com",
    phone: "+1 (555) 890-1234",
    class: "Beginner Quran",
    enrolledDate: "2025-04-03",
    attendance: "82%",
  },
]

export const classes = [
  {
    id: 1,
    name: "Beginner Quran",
    teacher: "Ustadh Abdullah Rahman",
    schedule: "Saturday, 10:00 AM",
    students: 12,
    sessions: [
      { id: 1, date: "Dec 14, 2025", status: "completed", present: 10, absent: 2 },
      { id: 2, date: "Dec 21, 2025", status: "scheduled", present: null, absent: null },
      { id: 3, date: "Dec 28, 2025", status: "scheduled", present: null, absent: null },
      { id: 4, date: "Jan 4, 2026", status: "scheduled", present: null, absent: null },
    ],
  },
  {
    id: 2,
    name: "Intermediate Tajweed",
    teacher: "Ustadh Abdullah Rahman",
    schedule: "Sunday, 2:00 PM",
    students: 12,
    sessions: [
      { id: 5, date: "Dec 15, 2025", status: "completed", present: 11, absent: 1 },
      { id: 6, date: "Dec 22, 2025", status: "scheduled", present: null, absent: null },
      { id: 7, date: "Dec 29, 2025", status: "holiday", present: null, absent: null },
      { id: 8, date: "Jan 5, 2026", status: "scheduled", present: null, absent: null },
    ],
  },
  {
    id: 3,
    name: "Advanced Memorization",
    teacher: "Ustadha Maryam Ali",
    schedule: "Saturday, 3:00 PM",
    students: 15,
    sessions: [
      { id: 9, date: "Dec 14, 2025", status: "completed", present: 15, absent: 0 },
      { id: 10, date: "Dec 21, 2025", status: "scheduled", present: null, absent: null },
      { id: 11, date: "Dec 28, 2025", status: "cancelled", present: null, absent: null },
      { id: 12, date: "Jan 4, 2026", status: "scheduled", present: null, absent: null },
    ],
  },
  {
    id: 4,
    name: "Arabic Language",
    teacher: "Ustadh Yusuf Khan",
    schedule: "Friday, 6:00 PM",
    students: 18,
    sessions: [
      { id: 13, date: "Dec 13, 2025", status: "completed", present: 16, absent: 2 },
      { id: 14, date: "Dec 20, 2025", status: "scheduled", present: null, absent: null },
      { id: 15, date: "Dec 27, 2025", status: "scheduled", present: null, absent: null },
      { id: 16, date: "Jan 3, 2026", status: "scheduled", present: null, absent: null },
    ],
  },
]